# Change these first
owner: sanderdatema # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Sander Datema
    url: https://sanderdatema.nl
  - name: Curated Distractions
    url: https://curateddistractions.com
  - name: Naakt Presenteren
    url: https://naaktpresenteren.nl
  - name: Return to Sander
    url: https://returntosander.net
  - name: Mastodon
    url: https://mastodon.returntosander.net
  - name: Stats
    url: https://stats.returntosander.net
  - name: Minio
    url: https://console.returntosander.net
  - name: Gitea
    url: https://git.returntosander.net

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Sander Datema
  introTitle: "**Upptime** Sander Datema."
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: sanderdatema

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
